### PR TITLE
Update to version 45 and force the use of portals

### PR DESCRIPTION
**Pull request by soumyaDghosh**

### CODE REVIEW

**Comment by soumyaDghosh** [comment]
@sergio-costas any thoughts on this? I think this can be merged too?

**Comment by sergio-costas** [comment]
@soumyaDghosh Please, rebase it against the last version in stable.

**Comment by soumyaDghosh** [comment]
Done

**Review by sergio-costas — APPROVED** [review]
LGTM

**Comment by sergio-costas** [comment]
@kenvandine I tested this and works fine. It can be merged.

**Review by kenvandine — CHANGES_REQUESTED** [review]
Please don't drop the plugs, these are still useful for people without portals.

**Comment by soumyaDghosh** [comment]
> Please don't drop the plugs, these are still useful for people without portals.

Both `home` and `removable-media`?

**Comment by kenvandine** [comment]
> > Please don't drop the plugs, these are still useful for people without portals.
> 
> Both `home` and `removable-media`?

Yeah, even if we don't auto connect removable-media at least the option is there.  And home is a must on a system without portals installed.

**Comment by soumyaDghosh** [comment]
Done

**Comment by soumyaDghosh** [comment]
@sergio-costas @kenvandine I think this can be merged now!

**Review by sergio-costas — APPROVED** [review]
LGTM

**Pull request merged**
